version: '3.8'

services:
  ubuntu_vps:
    image: ubuntu
    ports:
      - "2222:22"
    environment:
      - SSH_PORT=2222
    volumes:
      - ubuntu_data:/data
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    command: bash -c "apt update && apt install -y openssh-server && /usr/sbin/sshd -D"
    stdin_open: true
    tty: true
    mem_limit: 1g
    cpus: 0.5
    tmpfs:
      - /tmp

volumes:
  ubuntu_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=3G
